### ISSUE TITLE
1.1.11F1 broke departure sequence

### ISSUE THREAD

**Issue by ObservantOtter** [bcallender/AllAboard#2]
Please see save file @ https://filebin.net/o3uanoh73xl2oyf0
CS2 version is 1.1.11F1 (Oct 23, 2024 - the patch that "fixed a bug related to synching mods"). Also happened with the previous days' 1.1.10F1.
Included is a capture of a train station at center. The red train at the leftmost platform is about to depart (it passed the '5s to departure' to 'Waiting on passenger xxxx'). Pause the game immediately after loading because it will crash to desktop in short order.
AllAboard! settings: 1minute train; 2m bus.
I should note: I had used AllAboard! from somewhere around 1.6M to this current 2.8M. This city is reliant on AllAboard! and had worked without issue until the 1.1.10F1 update.

**Comment by bcallender** [comment]
@ObservantOtter thanks for the detailed report! I just pushed a new version of the mod 0.1.1 that should address this

**Comment by ObservantOtter** [comment]
This does indeed fix my crash issue. Trains, buses & trams are respecting dwell time & departing. Thanks for the fix. Closing this issue.
